import type { CanonicalBlock, CanonicalResponse } from '../../ir/types.ts';
import type { WireBody } from '../index.ts';

function text(blocks: CanonicalBlock[]): string { return blocks.filter((b): b is Extract<CanonicalBlock,{kind:'text'}> => b.kind==='text').map(b=>b.text).join(''); }
function tools(blocks: CanonicalBlock[]): Record<string, unknown>[] { return blocks.filter((b): b is Extract<CanonicalBlock,{kind:'tool_use'}>=>b.kind==='tool_use').map(b=>({id:b.id,type:'function',function:{name:b.namespace?`${b.namespace}__${b.name}`:b.name,arguments:JSON.stringify(b.input)}})); }
function anthropic(response: CanonicalResponse): WireBody { const blocks=response.message.blocks; return {id:'msg_canonical',type:'message',role:'assistant',content:blocks.map(b=>b.kind==='text'?{type:'text',text:b.text}:b.kind==='thinking'?{type:'thinking',thinking:b.text,signature:b.signature??''}:b.kind==='tool_use'?{type:'tool_use',id:b.id,name:b.namespace?`${b.namespace}__${b.name}`:b.name,input:b.input}:{type:'text',text:b.kind==='reasoning'?b.text:''}),model:response.model,stop_reason:response.stopReason,stop_sequence:null,usage:response.usage?{input_tokens:response.usage.inputTokens,output_tokens:response.usage.outputTokens,...(response.usage.cacheReadTokens?{cache_read_input_tokens:response.usage.cacheReadTokens}:{}),...(response.usage.cacheCreationTokens?{cache_creation_input_tokens:response.usage.cacheCreationTokens}:{})}:undefined}; }
function chat(response: CanonicalResponse): WireBody { const calls=tools(response.message.blocks); return {id:'chatcmpl-canonical',object:'chat.completion',created:Math.floor(Date.now()/1000),model:response.model,choices:[{index:0,message:{role:'assistant',content:text(response.message.blocks),...(response.message.blocks.some(b=>b.kind==='thinking')?{reasoning_content:response.message.blocks.filter((b):b is Extract<CanonicalBlock,{kind:'thinking'}>=>b.kind==='thinking').map(b=>b.text).join('')}:{}),...(calls.length?{tool_calls:calls}:{})},finish_reason:response.stopReason}],usage:response.usage?{prompt_tokens:response.usage.inputTokens+(response.usage.cacheReadTokens??0)+(response.usage.cacheCreationTokens??0),completion_tokens:response.usage.outputTokens,total_tokens:response.usage.inputTokens+response.usage.outputTokens+(response.usage.cacheReadTokens??0)+(response.usage.cacheCreationTokens??0)}:undefined}; }
function responses(response: CanonicalResponse): WireBody { const output: Record<string, unknown>[]=[]; const messageText=text(response.message.blocks); if(messageText) output.push({type:'message',role:'assistant',content:[{type:'output_text',text:messageText,annotations:[]}]}); for(const block of response.message.blocks) { if(block.kind==='tool_use') output.push(block.name==='computer'?{type:'computer_call',call_id:block.id,action:block.input,status:'completed'}:{type:'function_call',call_id:block.id,name:block.namespace?`${block.namespace}__${block.name}`:block.name,arguments:JSON.stringify(block.input),status:'completed'}); } return {id:'resp_canonical',object:'response',created_at:Math.floor(Date.now()/1000),model:response.model,output,status:response.finishReason==='completed'?'completed':'incomplete',usage:response.usage?{input_tokens:response.usage.inputTokens,output_tokens:response.usage.outputTokens,total_tokens:response.usage.inputTokens+response.usage.outputTokens}:undefined}; }
export const convertAnthropicResponseToOpenAI = (r: CanonicalResponse): WireBody => chat(r);
export const convertAnthropicResponseToOpenAIResponses = (r: CanonicalResponse): WireBody => responses(r);
export const convertOpenAIResponseToAnthropic = (r: CanonicalResponse): WireBody => anthropic(r);
export const convertOpenAIResponsesToAnthropic = (r: CanonicalResponse): WireBody => anthropic(r);
export const convertOpenAIResponseToOpenAIResponses = (r: CanonicalResponse): WireBody => responses(r);
export const convertOpenAIResponsesResponseToOpenAI = (r: CanonicalResponse): WireBody => chat(r);
export const anthropicToOpenAi = convertAnthropicResponseToOpenAI;
export const anthropicToResponses = convertAnthropicResponseToOpenAIResponses;
export const openAiToAnthropic = convertOpenAIResponseToAnthropic;
export const responsesToAnthropic = convertOpenAIResponsesToAnthropic;
export const chatToResponses = convertOpenAIResponseToOpenAIResponses;
export const responsesToChat = convertOpenAIResponsesResponseToOpenAI;
