/**
 * Generate TypeScript types from locales/zh/translation.json
 * Output: src/types/i18n.generated.ts
 *
 * Run: npx tsx scripts/generate-i18n-types.ts
 */

import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs'
import { resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const ROOT = resolve(__dirname, '..')

function loadJson(path: string): Record<string, unknown> {
  const fullPath = resolve(ROOT, path)
  if (!existsSync(fullPath)) {
    console.error(`Error: File not found: ${fullPath}`)
    process.exit(1)
  }
  const content = readFileSync(fullPath, 'utf-8')
  return JSON.parse(content)
}

/**
 * Collect all dot-path keys from a nested JSON object.
 * E.g., { admin: { nav: { dashboard: "x" } } } -> ["admin.nav.dashboard"]
 */
function collectKeys(obj: Record<string, unknown>, prefix = ''): string[] {
  const keys: string[] = []
  for (const [key, value] of Object.entries(obj)) {
    const fullKey = prefix ? `${prefix}.${key}` : key
    if (typeof value === 'object' && value !== null && !Array.isArray(value)) {
      keys.push(...collectKeys(value as Record<string, unknown>, fullKey))
    } else {
      keys.push(fullKey)
    }
  }
  return keys
}

/**
 * Generate a TypeScript union type of all translation keys.
 */
function generateType(keys: string[]): string {
  // Generate the type
  const typeLines = keys.map(k => `  | '${k}'`)
  return `// Auto-generated by scripts/generate-i18n-types.ts
// Do not edit manually. Run 'npm run generate:i18n-types' to update.

/**
 * All available translation keys as a union type.
 */
export type TranslationKey =
${typeLines.join('\n')}

/**
 * Type-safe translation function signature.
 * Use this in your code: t(key, options?)
 */
export type TFunction = (key: TranslationKey, options?: Record<string, unknown>) => string
`
}

// --- Main ---

const zh = loadJson('locales/zh/translation.json')
const en = loadJson('locales/en/translation.json')

const zhKeys = collectKeys(zh)
const enKeys = collectKeys(en)

// Find keys that are in one but not the other
const zhSet = new Set(zhKeys)
const enSet = new Set(enKeys)

const missingInEn = zhKeys.filter(k => !enSet.has(k))
const missingInZh = enKeys.filter(k => !zhSet.has(k))

if (missingInEn.length > 0) {
  console.warn(`Warning: ${missingInEn.length} keys in zh.json but not in en.json:`)
  missingInEn.forEach(k => console.warn(`  - ${k}`))
}

if (missingInZh.length > 0) {
  console.warn(`Warning: ${missingInZh.length} keys in en.json but not in zh.json:`)
  missingInZh.forEach(k => console.warn(`  - ${k}`))
}

// Use the union of both as the type
const allKeys = [...new Set([...zhKeys, ...enKeys])].sort()
const outputDir = resolve(ROOT, 'src', 'types')
mkdirSync(outputDir, { recursive: true })

const output = generateType(allKeys)
const outputPath = resolve(outputDir, 'i18n.generated.ts')
writeFileSync(outputPath, output, 'utf-8')
console.log(`Generated ${allKeys.length} translation keys → ${outputPath}`)
console.log(`  zh: ${zhKeys.length} keys`)
console.log(`  en: ${enKeys.length} keys`)
if (missingInEn.length > 0) console.log(`  Missing in en: ${missingInEn.length}`)
if (missingInZh.length > 0) console.log(`  Missing in zh: ${missingInZh.length}`)
